# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import network_and_telnet_pb2 as network__and__telnet__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in network_and_telnet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConnectivityServiceStub(object):
    """Service to check server health and connectivity
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckServerHealth = channel.unary_unary(
                '/tradeoperation.ConnectivityService/CheckServerHealth',
                request_serializer=network__and__telnet__pb2.NetworkInfoRequest.SerializeToString,
                response_deserializer=network__and__telnet__pb2.NetworkInfoResponse.FromString,
                _registered_method=True)


class ConnectivityServiceServicer(object):
    """Service to check server health and connectivity
    """

    def CheckServerHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectivityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckServerHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckServerHealth,
                    request_deserializer=network__and__telnet__pb2.NetworkInfoRequest.FromString,
                    response_serializer=network__and__telnet__pb2.NetworkInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradeoperation.ConnectivityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradeoperation.ConnectivityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectivityService(object):
    """Service to check server health and connectivity
    """

    @staticmethod
    def CheckServerHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradeoperation.ConnectivityService/CheckServerHealth',
            network__and__telnet__pb2.NetworkInfoRequest.SerializeToString,
            network__and__telnet__pb2.NetworkInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TelnetServiceStub(object):
    """Service to execute commands over Telnet
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/tradeoperation.TelnetService/ExecuteCommand',
                request_serializer=network__and__telnet__pb2.CommandRequest.SerializeToString,
                response_deserializer=network__and__telnet__pb2.CommandResponse.FromString,
                _registered_method=True)


class TelnetServiceServicer(object):
    """Service to execute commands over Telnet
    """

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelnetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=network__and__telnet__pb2.CommandRequest.FromString,
                    response_serializer=network__and__telnet__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tradeoperation.TelnetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tradeoperation.TelnetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelnetService(object):
    """Service to execute commands over Telnet
    """

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tradeoperation.TelnetService/ExecuteCommand',
            network__and__telnet__pb2.CommandRequest.SerializeToString,
            network__and__telnet__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
