# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network_and_telnet.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'network_and_telnet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18network_and_telnet.proto\x12\x0etradeoperation\"\'\n\x12NetworkInfoRequest\x12\x11\n\tclient_ip\x18\x01 \x01(\t\":\n\x13NetworkInfoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nis_healthy\x18\x02 \x01(\x08\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2s\n\x13\x43onnectivityService\x12\\\n\x11\x43heckServerHealth\x12\".tradeoperation.NetworkInfoRequest\x1a#.tradeoperation.NetworkInfoResponse2b\n\rTelnetService\x12Q\n\x0e\x45xecuteCommand\x12\x1e.tradeoperation.CommandRequest\x1a\x1f.tradeoperation.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_and_telnet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKINFOREQUEST']._serialized_start=44
  _globals['_NETWORKINFOREQUEST']._serialized_end=83
  _globals['_NETWORKINFORESPONSE']._serialized_start=85
  _globals['_NETWORKINFORESPONSE']._serialized_end=143
  _globals['_COMMANDREQUEST']._serialized_start=145
  _globals['_COMMANDREQUEST']._serialized_end=178
  _globals['_COMMANDRESPONSE']._serialized_start=180
  _globals['_COMMANDRESPONSE']._serialized_end=213
  _globals['_CONNECTIVITYSERVICE']._serialized_start=215
  _globals['_CONNECTIVITYSERVICE']._serialized_end=330
  _globals['_TELNETSERVICE']._serialized_start=332
  _globals['_TELNETSERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
